### ISSUE TITLE
Turn autohintexe into a Python module

### ISSUE THREAD

**Issue by khaledhosny** [khaledhosny/psautohint#2]

**Comment by anthrotype** [comment]
Hey Khaled, nice seeing that you started this project!
Long time ago (before fontmake was a thing) I also attempted to wrap makeotf in a CPython extension module

https://github.com/anthrotype/makeotflib-py

If I were to do it now, I'd probably use cython instead of a hand coded C extension module.

The nice thing about that experiment was that I managed to build the afdko C libraries without GNU make using only setuptools.

Maybe we could attempt the same approach here for the autohinter, so that we build a static library which is then linked to the cython wrapper.

I'll be quite busy with other things next week, so I can't guarantee anything in the immediate.

Anyway, thanks for putting this up. Look forward to hooking this up to fontmake and TruFont!

**Comment by khaledhosny** [comment]
The Makefile I have now is rather plain, so it shouldn’t be hard to to use setuptools instead.
